In [14]:
import pandas as pd

df = pd.read_csv("../data/raw/Base.csv")

df.head()

,fraud_bool,income,name_email_similarity,prev_address_months_count,current_address_months_count,customer_age,days_since_request,intended_balcon_amount,payment_type,zip_count_4w,...,has_other_cards,proposed_credit_limit,foreign_request,source,session_length_in_minutes,device_os,keep_alive_session,device_distinct_emails_8w,device_fraud_count,month
0,0,0.3,0.986506,-1,25,40,0.006735,102.453711,AA,1059,...,0,1500.0,0,INTERNET,16.224843,linux,1,1,0,0
1,0,0.8,0.617426,-1,89,20,0.010095,-0.849551,AD,1658,...,0,1500.0,0,INTERNET,3.363854,other,1,1,0,0
2,0,0.8,0.996707,9,14,40,0.012316,-1.490386,AB,1095,...,0,200.0,0,INTERNET,22.730559,windows,0,1,0,0
3,0,0.6,0.475100,11,14,30,0.006991,-1.863101,AB,3483,...,0,200.0,0,INTERNET,15.215816,linux,1,1,0,0
4,0,0.9,0.842307,-1,29,40,5.742626,47.152498,AA,2339,...,0,200.0,0,INTERNET,3.743048,other,0,1,0,0

In [4]:
df.shape

(1000000, 32)

In [5]:
df.columns.tolist()

['fraud_bool',
 'income',
 'name_email_similarity',
 'prev_address_months_count',
 'current_address_months_count',
 'customer_age',
 'days_since_request',
 'intended_balcon_amount',
 'payment_type',
 'zip_count_4w',
 'velocity_6h',
 'velocity_24h',
 'velocity_4w',
 'bank_branch_count_8w',
 'date_of_birth_distinct_emails_4w',
 'employment_status',
 'credit_risk_score',
 'email_is_free',
 'housing_status',
 'phone_home_valid',
 'phone_mobile_valid',
 'bank_months_count',
 'has_other_cards',
 'proposed_credit_limit',
 'foreign_request',
 'source',
 'session_length_in_minutes',
 'device_os',
 'keep_alive_session',
 'device_distinct_emails_8w',
 'device_fraud_count',
 'month']

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 32 columns):
 #   Column                            Non-Null Count    Dtype
---  ------                            --------------    -----
 0   fraud_bool                        1000000 non-null  int64
 1   income                            1000000 non-null  float64
 2   name_email_similarity             1000000 non-null  float64
 3   prev_address_months_count         1000000 non-null  int64
 4   current_address_months_count      1000000 non-null  int64
 5   customer_age                      1000000 non-null  int64
 6   days_since_request                1000000 non-null  float64
 7   intended_balcon_amount            1000000 non-null  float64
 8   payment_type                      1000000 non-null  str
 9   zip_count_4w                      1000000 non-null  int64
 10  velocity_6h                       1000000 non-null  float64
 11  velocity_24h                      1000000 non-null  float64
 12  velocity_4w                       1000000 non-null  float64
 13  bank_branch_count_8w              1000000 non-null  int64
 14  date_of_birth_distinct_emails_4w  1000000 non-null  int64
 15  employment_status                 1000000 non-null  str
 16  credit_risk_score                 1000000 non-null  int64
 17  email_is_free                     1000000 non-null  int64
 18  housing_status                    1000000 non-null  str
 19  phone_home_valid                  1000000 non-null  int64
 20  phone_mobile_valid                1000000 non-null  int64
 21  bank_months_count                 1000000 non-null  int64
 22  has_other_cards                   1000000 non-null  int64
 23  proposed_credit_limit             1000000 non-null  float64
 24  foreign_request                   1000000 non-null  int64
 25  source                            1000000 non-null  str
 26  session_length_in_minutes         1000000 non-null  float64
 27  device_os                         1000000 non-null  str
 28  keep_alive_session                1000000 non-null  int64
 29  device_distinct_emails_8w         1000000 non-null  int64
 30  device_fraud_count                1000000 non-null  int64
 31  month                             1000000 non-null  int64
dtypes: float64(9), int64(18), str(5)
memory usage: 262.9 MB

In [7]:
df["fraud_bool"].value_counts()

fraud_bool
0    988971
1     11029
Name: count, dtype: int64

In [8]:
df["fraud_bool"].value_counts(normalize=True) * 100

fraud_bool
0    98.8971
1     1.1029
Name: proportion, dtype: float64

In [9]:
df.isnull().sum().sort_values(ascending=False)

fraud_bool                          0
income                              0
name_email_similarity               0
prev_address_months_count           0
current_address_months_count        0
customer_age                        0
days_since_request                  0
intended_balcon_amount              0
payment_type                        0
zip_count_4w                        0
velocity_6h                         0
velocity_24h                        0
velocity_4w                         0
bank_branch_count_8w                0
date_of_birth_distinct_emails_4w    0
employment_status                   0
credit_risk_score                   0
email_is_free                       0
housing_status                      0
phone_home_valid                    0
phone_mobile_valid                  0
bank_months_count                   0
has_other_cards                     0
proposed_credit_limit               0
foreign_request                     0
source                              0
session_length_in_minutes           0
device_os                           0
keep_alive_session                  0
device_distinct_emails_8w           0
device_fraud_count                  0
month                               0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
fraud_bool,1000000.0,0.011029,0.104438,0.000000e+00,0.000000,0.000000,0.000000,1.000000
income,1000000.0,0.562696,0.290343,1.000000e-01,0.300000,0.600000,0.800000,0.900000
name_email_similarity,1000000.0,0.493694,0.289125,1.434550e-06,0.225216,0.492153,0.755567,0.999999
prev_address_months_count,1000000.0,16.718568,44.046230,-1.000000e+00,-1.000000,-1.000000,12.000000,383.000000
current_address_months_count,1000000.0,86.587867,88.406599,-1.000000e+00,19.000000,52.000000,130.000000,428.000000
customer_age,1000000.0,33.689080,12.025799,1.000000e+01,20.000000,30.000000,40.000000,90.000000
days_since_request,1000000.0,1.025705,5.381835,4.036860e-09,0.007193,0.015176,0.026331,78.456904
intended_balcon_amount,1000000.0,8.661499,20.236155,-1.553055e+01,-1.181488,-0.830507,4.984176,112.956928
zip_count_4w,1000000.0,1572.692049,1005.374565,1.000000e+00,894.000000,1263.000000,1944.000000,6700.000000
velocity_6h,1000000.0,5665.296605,3009.380665,-1.706031e+02,3436.365848,5319.769349,7680.717827,16715.565404
velocity_24h,1000000.0,4769.781965,1479.212612,1.300307e+03,3593.179135,4749.921161,5752.574191,9506.896596
velocity_4w,1000000.0,4856.324016,919.843934,2.825748e+03,4268.368423,4913.436941,5488.083356,6994.764201
bank_branch_count_8w,1000000.0,184.361849,459.625329,0.000000e+00,1.000000,9.000000,25.000000,2385.000000
date_of_birth_distinct_emails_4w,1000000.0,9.503544,5.033792,0.000000e+00,6.000000,9.000000,13.000000,39.000000
credit_risk_score,1000000.0,130.989595,69.681812,-1.700000e+02,83.000000,122.000000,178.000000,389.000000
email_is_free,1000000.0,0.529886,0.499106,0.000000e+00,0.000000,1.000000,1.000000,1.000000
phone_home_valid,1000000.0,0.417077,0.493076,0.000000e+00,0.000000,0.000000,1.000000,1.000000
phone_mobile_valid,1000000.0,0.889676,0.313293,0.000000e+00,1.000000,1.000000,1.000000,1.000000
bank_months_count,1000000.0,10.839303,12.116875,-1.000000e+00,-1.000000,5.000000,25.000000,32.000000
has_other_cards,1000000.0,0.222988,0.416251,0.000000e+00,0.000000,0.000000,0.000000,1.000000
proposed_credit_limit,1000000.0,515.851010,487.559902,1.900000e+02,200.000000,200.000000,500.000000,2100.000000
foreign_request,1000000.0,0.025242,0.156859,0.000000e+00,0.000000,0.000000,0.000000,1.000000
session_length_in_minutes,1000000.0,7.544940,8.033106,-1.000000e+00,3.103053,5.114321,8.866131,85.899143
keep_alive_session,1000000.0,0.576947,0.494044,0.000000e+00,0.000000,1.000000,1.000000,1.000000
device_distinct_emails_8w,1000000.0,1.018312,0.180761,-1.000000e+00,1.000000,1.000000,1.000000,2.000000
device_fraud_count,1000000.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
month,1000000.0,3.288674,2.209994,0.000000e+00,1.000000,3.000000,5.000000,7.000000

In [12]:
df.select_dtypes(include="object").columns

C:\Users\ASUS\AppData\Local\Temp\ipykernel_23288\1196084386.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object").columns

Index(['payment_type', 'employment_status', 'housing_status', 'source',
       'device_os'],
      dtype='str')

In [13]:
for col in df.select_dtypes(include="object").columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts())

--- payment_type ---
payment_type
AB    370554
AA    258249
AC    252071
AD    118837
AE       289
Name: count, dtype: int64

--- employment_status ---
employment_status
CA    730252
CB    138288
CF     44034
CC     37758
CD     26522
CE     22693
CG       453
Name: count, dtype: int64

--- housing_status ---
housing_status
BC    372143
BB    260965
BA    169675
BE    169135
BD     26161
BF      1669
BG       252
Name: count, dtype: int64

--- source ---
source
INTERNET    992952
TELEAPP       7048
Name: count, dtype: int64

--- device_os ---
device_os
other        342728
linux        332712
windows      263506
macintosh     53826
x11            7228
Name: count, dtype: int64

C:\Users\ASUS\AppData\Local\Temp\ipykernel_23288\3875818361.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns: